バージョン番号を適切なフォーマットに整形するようにした

diff --git a/.github/workflows/publish-to-nuget.yml b/.github/workflows/publish-to-nuget.yml
--- a/.github/workflows/publish-to-nuget.yml
+++ b/.github/workflows/publish-to-nuget.yml
@@ -33,6 +33,30 @@ jobs:
           echo "Default version was set"
           $Version = '1.0.0'
         }
+        else
+        {
+          $VersionCore,$PreReleaseEtc = $Version.Split('-', 2)
+          $Major,$Minor,$Build,$Revision = $VersionCore.Split('.', 4)
+
+          If ([string]::IsNullOrEmpty($Major))
+          {
+            Write-Error "Major Version Not Found"
+            exit 1
+          }
+
+          $Minor = [string]::IsNullOrEmpty($Minor) ? 0 : [int]$Minor
+          $Build = [string]::IsNullOrEmpty($Build) ? 0 : [int]$Build
+          $Revision = [string]::IsNullOrEmpty($Revision) ? 0 : [int]$Revision
+
+          If (![string]::IsNullOrEmpty($PreReleaseEtc))
+          {
+            $PreReleaseEtc = "-$PreReleaseEtc"
+          }
+          $Revision = $Revision -le 0 ? '' : ".$Revision"
+          
+          $Version = "$Major.$Minor.$Build$Revision$PreReleaseEtc"
+        }
+
         echo "Version ... '$Version'"
         echo "VERSION=$Version" >> $env:GITHUB_OUTPUT
 
